// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_assignment.Data;

#nullable disable

namespace web_assignment.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("web_assignment.Data.QuestionModel", b =>
                {
                    b.Property<int>("QuestionModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<string>("correctOption")
                        .HasColumnType("TEXT");

                    b.Property<string>("optionOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("optionThree")
                        .HasColumnType("TEXT");

                    b.Property<string>("optionTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionModelId");

                    b.ToTable("QuestionModels");
                });
#pragma warning restore 612, 618
        }
    }
}
